/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Candle {
    #[serde(rename = "figi")]
    pub figi: String,
    #[serde(rename = "interval")]
    pub interval: crate::tinkoff_api::models::CandleResolution,
    #[serde(rename = "o")]
    pub o: f64,
    #[serde(rename = "c")]
    pub c: f64,
    #[serde(rename = "h")]
    pub h: f64,
    #[serde(rename = "l")]
    pub l: f64,
    #[serde(rename = "v")]
    pub v: i32,
    /// ISO8601
    #[serde(rename = "time")]
    pub time: String,
}

impl Candle {
    pub fn new(figi: String, interval: crate::tinkoff_api::models::CandleResolution, o: f64, c: f64, h: f64, l: f64, v: i32, time: String) -> Candle {
        Candle {
            figi,
            interval,
            o,
            c,
            h,
            l,
            v,
            time,
        }
    }
}


