/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */

/// CandleResolution : Интервал свечи и допустимый промежуток запроса: - 1min [1 minute, 1 day] - 2min [2 minutes, 1 day] - 3min [3 minutes, 1 day] - 5min [5 minutes, 1 day] - 10min [10 minutes, 1 day] - 15min [15 minutes, 1 day] - 30min [30 minutes, 1 day] - hour [1 hour, 7 days] - day [1 day, 1 year] - week [7 days, 2 years] - month [1 month, 10 years] 

/// Интервал свечи и допустимый промежуток запроса: - 1min [1 minute, 1 day] - 2min [2 minutes, 1 day] - 3min [3 minutes, 1 day] - 5min [5 minutes, 1 day] - 10min [10 minutes, 1 day] - 15min [15 minutes, 1 day] - 30min [30 minutes, 1 day] - hour [1 hour, 7 days] - day [1 day, 1 year] - week [7 days, 2 years] - month [1 month, 10 years] 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CandleResolution {
    #[serde(rename = "1min")]
    _1min,
    #[serde(rename = "2min")]
    _2min,
    #[serde(rename = "3min")]
    _3min,
    #[serde(rename = "5min")]
    _5min,
    #[serde(rename = "10min")]
    _10min,
    #[serde(rename = "15min")]
    _15min,
    #[serde(rename = "30min")]
    _30min,
    #[serde(rename = "hour")]
    Hour,
    #[serde(rename = "day")]
    Day,
    #[serde(rename = "week")]
    Week,
    #[serde(rename = "month")]
    Month,

}

impl ToString for CandleResolution {
    fn to_string(&self) -> String {
        match self {
            Self::_1min => String::from("1min"),
            Self::_2min => String::from("2min"),
            Self::_3min => String::from("3min"),
            Self::_5min => String::from("5min"),
            Self::_10min => String::from("10min"),
            Self::_15min => String::from("15min"),
            Self::_30min => String::from("30min"),
            Self::Hour => String::from("hour"),
            Self::Day => String::from("day"),
            Self::Week => String::from("week"),
            Self::Month => String::from("month"),
        }
    }
}




