/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Candles {
    #[serde(rename = "figi")]
    pub figi: String,
    #[serde(rename = "interval")]
    pub interval: crate::tinkoff_api::models::CandleResolution,
    #[serde(rename = "candles")]
    pub candles: Vec<crate::tinkoff_api::models::Candle>,
}

impl Candles {
    pub fn new(figi: String, interval: crate::tinkoff_api::models::CandleResolution, candles: Vec<crate::tinkoff_api::models::Candle>) -> Candles {
        Candles {
            figi,
            interval,
            candles,
        }
    }
}


