/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Currencies {
    #[serde(rename = "currencies")]
    pub currencies: Vec<crate::tinkoff_api::models::CurrencyPosition>,
}

impl Currencies {
    pub fn new(currencies: Vec<crate::tinkoff_api::models::CurrencyPosition>) -> Currencies {
        Currencies {
            currencies,
        }
    }
}


