/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Currency {
    #[serde(rename = "RUB")]
    RUB,
    #[serde(rename = "USD")]
    USD,
    #[serde(rename = "EUR")]
    EUR,
    #[serde(rename = "GBP")]
    GBP,
    #[serde(rename = "HKD")]
    HKD,
    #[serde(rename = "CHF")]
    CHF,
    #[serde(rename = "JPY")]
    JPY,
    #[serde(rename = "CNY")]
    CNY,
    #[serde(rename = "TRY")]
    _TRY,

}

impl ToString for Currency {
    fn to_string(&self) -> String {
        match self {
            Self::RUB => String::from("RUB"),
            Self::USD => String::from("USD"),
            Self::EUR => String::from("EUR"),
            Self::GBP => String::from("GBP"),
            Self::HKD => String::from("HKD"),
            Self::CHF => String::from("CHF"),
            Self::JPY => String::from("JPY"),
            Self::CNY => String::from("CNY"),
            Self::_TRY => String::from("TRY"),
        }
    }
}




