/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurrencyPosition {
    #[serde(rename = "currency")]
    pub currency: crate::tinkoff_api::models::Currency,
    #[serde(rename = "balance")]
    pub balance: f64,
    #[serde(rename = "blocked", skip_serializing_if = "Option::is_none")]
    pub blocked: Option<f64>,
}

impl CurrencyPosition {
    pub fn new(currency: crate::tinkoff_api::models::Currency, balance: f64) -> CurrencyPosition {
        CurrencyPosition {
            currency,
            balance,
            blocked: None,
        }
    }
}


