/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Empty {
    #[serde(rename = "trackingId")]
    pub tracking_id: String,
    #[serde(rename = "payload")]
    pub payload: serde_json::Value,
    #[serde(rename = "status")]
    pub status: String,
}

impl Empty {
    pub fn new(tracking_id: String, payload: serde_json::Value, status: String) -> Empty {
        Empty {
            tracking_id,
            payload,
            status,
        }
    }
}


