/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketOrderRequest {
    #[serde(rename = "lots")]
    pub lots: i32,
    #[serde(rename = "operation")]
    pub operation: crate::tinkoff_api::models::OperationType,
}

impl MarketOrderRequest {
    pub fn new(lots: i32, operation: crate::tinkoff_api::models::OperationType) -> MarketOrderRequest {
        MarketOrderRequest {
            lots,
            operation,
        }
    }
}


