/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketInstrumentList {
    #[serde(rename = "total")]
    pub total: f32,
    #[serde(rename = "instruments")]
    pub instruments: Vec<crate::tinkoff_api::models::MarketInstrument>,
}

impl MarketInstrumentList {
    pub fn new(total: f32, instruments: Vec<crate::tinkoff_api::models::MarketInstrument>) -> MarketInstrumentList {
        MarketInstrumentList {
            total,
            instruments,
        }
    }
}


