/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperationTypeWithCommission {
    #[serde(rename = "Buy")]
    Buy,
    #[serde(rename = "BuyCard")]
    BuyCard,
    #[serde(rename = "Sell")]
    Sell,
    #[serde(rename = "BrokerCommission")]
    BrokerCommission,
    #[serde(rename = "ExchangeCommission")]
    ExchangeCommission,
    #[serde(rename = "ServiceCommission")]
    ServiceCommission,
    #[serde(rename = "MarginCommission")]
    MarginCommission,
    #[serde(rename = "OtherCommission")]
    OtherCommission,
    #[serde(rename = "PayIn")]
    PayIn,
    #[serde(rename = "PayOut")]
    PayOut,
    #[serde(rename = "Tax")]
    Tax,
    #[serde(rename = "TaxLucre")]
    TaxLucre,
    #[serde(rename = "TaxDividend")]
    TaxDividend,
    #[serde(rename = "TaxCoupon")]
    TaxCoupon,
    #[serde(rename = "TaxBack")]
    TaxBack,
    #[serde(rename = "Repayment")]
    Repayment,
    #[serde(rename = "PartRepayment")]
    PartRepayment,
    #[serde(rename = "Coupon")]
    Coupon,
    #[serde(rename = "Dividend")]
    Dividend,
    #[serde(rename = "SecurityIn")]
    SecurityIn,
    #[serde(rename = "SecurityOut")]
    SecurityOut,

}

impl ToString for OperationTypeWithCommission {
    fn to_string(&self) -> String {
        match self {
            Self::Buy => String::from("Buy"),
            Self::BuyCard => String::from("BuyCard"),
            Self::Sell => String::from("Sell"),
            Self::BrokerCommission => String::from("BrokerCommission"),
            Self::ExchangeCommission => String::from("ExchangeCommission"),
            Self::ServiceCommission => String::from("ServiceCommission"),
            Self::MarginCommission => String::from("MarginCommission"),
            Self::OtherCommission => String::from("OtherCommission"),
            Self::PayIn => String::from("PayIn"),
            Self::PayOut => String::from("PayOut"),
            Self::Tax => String::from("Tax"),
            Self::TaxLucre => String::from("TaxLucre"),
            Self::TaxDividend => String::from("TaxDividend"),
            Self::TaxCoupon => String::from("TaxCoupon"),
            Self::TaxBack => String::from("TaxBack"),
            Self::Repayment => String::from("Repayment"),
            Self::PartRepayment => String::from("PartRepayment"),
            Self::Coupon => String::from("Coupon"),
            Self::Dividend => String::from("Dividend"),
            Self::SecurityIn => String::from("SecurityIn"),
            Self::SecurityOut => String::from("SecurityOut"),
        }
    }
}




