/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Operations {
    #[serde(rename = "operations")]
    pub operations: Vec<crate::tinkoff_api::models::Operation>,
}

impl Operations {
    pub fn new(operations: Vec<crate::tinkoff_api::models::Operation>) -> Operations {
        Operations {
            operations,
        }
    }
}


