/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */

/// OperationStatus : Статус заявки

/// Статус заявки
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperationStatus {
    #[serde(rename = "Done")]
    Done,
    #[serde(rename = "Decline")]
    Decline,
    #[serde(rename = "Progress")]
    Progress,

}

impl ToString for OperationStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Done => String::from("Done"),
            Self::Decline => String::from("Decline"),
            Self::Progress => String::from("Progress"),
        }
    }
}




