/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderResponse {
    #[serde(rename = "price")]
    pub price: f64,
    #[serde(rename = "quantity")]
    pub quantity: i32,
}

impl OrderResponse {
    pub fn new(price: f64, quantity: i32) -> OrderResponse {
        OrderResponse {
            price,
            quantity,
        }
    }
}


