/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrdersResponse {
    #[serde(rename = "trackingId")]
    pub tracking_id: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "payload")]
    pub payload: Vec<crate::tinkoff_api::models::Order>,
}

impl OrdersResponse {
    pub fn new(tracking_id: String, status: String, payload: Vec<crate::tinkoff_api::models::Order>) -> OrdersResponse {
        OrdersResponse {
            tracking_id,
            status,
            payload,
        }
    }
}


