/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Order {
    #[serde(rename = "orderId")]
    pub order_id: String,
    #[serde(rename = "figi")]
    pub figi: String,
    #[serde(rename = "operation")]
    pub operation: crate::tinkoff_api::models::OperationType,
    #[serde(rename = "status")]
    pub status: crate::tinkoff_api::models::OrderStatus,
    #[serde(rename = "requestedLots")]
    pub requested_lots: i32,
    #[serde(rename = "executedLots")]
    pub executed_lots: i32,
    #[serde(rename = "type")]
    pub _type: crate::tinkoff_api::models::OrderType,
    #[serde(rename = "price")]
    pub price: f64,
}

impl Order {
    pub fn new(order_id: String, figi: String, operation: crate::tinkoff_api::models::OperationType, status: crate::tinkoff_api::models::OrderStatus, requested_lots: i32, executed_lots: i32, _type: crate::tinkoff_api::models::OrderType, price: f64) -> Order {
        Order {
            order_id,
            figi,
            operation,
            status,
            requested_lots,
            executed_lots,
            _type,
            price,
        }
    }
}


