/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */

/// OrderStatus : Статус заявки

/// Статус заявки
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderStatus {
    #[serde(rename = "New")]
    New,
    #[serde(rename = "PartiallyFill")]
    PartiallyFill,
    #[serde(rename = "Fill")]
    Fill,
    #[serde(rename = "Cancelled")]
    Cancelled,
    #[serde(rename = "Replaced")]
    Replaced,
    #[serde(rename = "PendingCancel")]
    PendingCancel,
    #[serde(rename = "Rejected")]
    Rejected,
    #[serde(rename = "PendingReplace")]
    PendingReplace,
    #[serde(rename = "PendingNew")]
    PendingNew,

}

impl ToString for OrderStatus {
    fn to_string(&self) -> String {
        match self {
            Self::New => String::from("New"),
            Self::PartiallyFill => String::from("PartiallyFill"),
            Self::Fill => String::from("Fill"),
            Self::Cancelled => String::from("Cancelled"),
            Self::Replaced => String::from("Replaced"),
            Self::PendingCancel => String::from("PendingCancel"),
            Self::Rejected => String::from("Rejected"),
            Self::PendingReplace => String::from("PendingReplace"),
            Self::PendingNew => String::from("PendingNew"),
        }
    }
}




