/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Portfolio {
    #[serde(rename = "positions")]
    pub positions: Vec<crate::tinkoff_api::models::PortfolioPosition>,
}

impl Portfolio {
    pub fn new(positions: Vec<crate::tinkoff_api::models::PortfolioPosition>) -> Portfolio {
        Portfolio {
            positions,
        }
    }
}


