/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxSetCurrencyBalanceRequest {
    #[serde(rename = "currency")]
    pub currency: crate::tinkoff_api::models::SandboxCurrency,
    #[serde(rename = "balance")]
    pub balance: f64,
}

impl SandboxSetCurrencyBalanceRequest {
    pub fn new(currency: crate::tinkoff_api::models::SandboxCurrency, balance: f64) -> SandboxSetCurrencyBalanceRequest {
        SandboxSetCurrencyBalanceRequest {
            currency,
            balance,
        }
    }
}


