/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxRegisterRequest {
    #[serde(rename = "brokerAccountType", skip_serializing_if = "Option::is_none")]
    pub broker_account_type: Option<crate::tinkoff_api::models::BrokerAccountType>,
}

impl SandboxRegisterRequest {
    pub fn new() -> SandboxRegisterRequest {
        SandboxRegisterRequest {
            broker_account_type: None,
        }
    }
}


