/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SandboxSetPositionBalanceRequest {
    #[serde(rename = "figi", skip_serializing_if = "Option::is_none")]
    pub figi: Option<String>,
    #[serde(rename = "balance")]
    pub balance: f64,
}

impl SandboxSetPositionBalanceRequest {
    pub fn new(balance: f64) -> SandboxSetPositionBalanceRequest {
        SandboxSetPositionBalanceRequest {
            figi: None,
            balance,
        }
    }
}


