/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TradeStatus {
    #[serde(rename = "NormalTrading")]
    NormalTrading,
    #[serde(rename = "NotAvailableForTrading")]
    NotAvailableForTrading,

}

impl ToString for TradeStatus {
    fn to_string(&self) -> String {
        match self {
            Self::NormalTrading => String::from("NormalTrading"),
            Self::NotAvailableForTrading => String::from("NotAvailableForTrading"),
        }
    }
}




