/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccounts {
    #[serde(rename = "accounts")]
    pub accounts: Vec<crate::tinkoff_api::models::UserAccount>,
}

impl UserAccounts {
    pub fn new(accounts: Vec<crate::tinkoff_api::models::UserAccount>) -> UserAccounts {
        UserAccounts {
            accounts,
        }
    }
}


