/*
 * OpenAPI
 *
 * tinkoff.ru/invest OpenAPI.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: al.a.volkov@tinkoff.ru
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccount {
    #[serde(rename = "brokerAccountType")]
    pub broker_account_type: crate::tinkoff_api::models::BrokerAccountType,
    #[serde(rename = "brokerAccountId")]
    pub broker_account_id: String,
}

impl UserAccount {
    pub fn new(broker_account_type: crate::tinkoff_api::models::BrokerAccountType, broker_account_id: String) -> UserAccount {
        UserAccount {
            broker_account_type,
            broker_account_id,
        }
    }
}


